services:
  accounts:
    image: "ngleanhvu/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservices-network

  cards:
    image: "ngleanhvu/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservices-network

  loans:
    image: "ngleanhvu/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: "bridge"