global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'accounts'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['accounts:8080']
  - job_name: 'loans'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['loans:8090']
  - job_name: 'cards'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cards:9000']
  - job_name: "gatewayserver"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gatewayserver:8072']
  - job_name: "eureka"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka:8070']
  - job_name: "configserver"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['configserver:8071']
